apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-support-api
  namespace: ai-support

spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Never