apiVersion: apps/v1
kind: Deployment
metadata:
  name: restart-test
  namespace: ai-support

spec:
  replicas: 1

  selector:
    matchLabels:
      app: restart-test

  template:
    metadata:
      labels:
        app: restart-test

    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80