"""rename pending actions state index

Revision ID: 0a0a0ec69dea
Revises: 9490341f8863
Create Date: 2026-09-13 07:57:42.156833

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a0a0ec69dea"
down_revision: str | Sequence[str] | None = "9490341f8863"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_incident_actions_state"), table_name="pending_actions")
    op.create_index(op.f("ix_pending_actions_state"), "pending_actions", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_actions_state"), table_name="pending_actions")
    op.create_index(
        op.f("ix_pending_incident_actions_state"),
        "pending_actions",
        ["state"],
        unique=False,
    )
    # ### end Alembic commands ###
