"""add users incidents and pending incident actions

Revision ID: 0d3486e09c31
Revises: 5767c5d2d4bc
Create Date: 2026-09-09 12:27:04.860543

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d3486e09c31"
down_revision: str | Sequence[str] | None = "5767c5d2d4bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("service_name", sa.String(length=120), nullable=True),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_table(
        "pending_incident_actions",
        sa.Column("approval_id", sa.String(length=32), nullable=False),
        sa.Column("requested_by", sa.String(length=120), nullable=False),
        sa.Column("incident_title", sa.String(length=120), nullable=False),
        sa.Column("incident_description", sa.Text(), nullable=False),
        sa.Column("incident_severity", sa.String(length=20), nullable=False),
        sa.Column("service_name", sa.String(length=120), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("executed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=512), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("pending_incident_actions")
    op.drop_table("incidents")
    # ### end Alembic commands ###
