"""add action trace correlation fields

Revision ID: 17a2bbefb934
Revises: 184e6519dfc6
Create Date: 2026-09-17 21:55:14.719429

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17a2bbefb934"
down_revision: str | Sequence[str] | None = "184e6519dfc6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pending_actions", sa.Column("origin_trace_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "pending_actions", sa.Column("origin_request_id", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pending_actions", "origin_request_id")
    op.drop_column("pending_actions", "origin_trace_id")
    # ### end Alembic commands ###
