"""add resource permissions

Revision ID: 184e6519dfc6
Revises: 5ec6d3e6acae
Create Date: 2026-09-14 02:53:26.532779

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "184e6519dfc6"
down_revision: str | Sequence[str] | None = "5ec6d3e6acae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_permissions",
        sa.Column("permission_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("permission", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_value", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("permission_id"),
        sa.UniqueConstraint(
            "username",
            "permission",
            "resource_type",
            "resource_value",
            name="uq_resource_permission",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource_permissions")
    # ### end Alembic commands ###
