"""add external identity to users

Revision ID: 5ec6d3e6acae
Revises: 0a0a0ec69dea
Create Date: 2026-09-14 00:27:07.083206

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ec6d3e6acae"
down_revision: str | Sequence[str] | None = "0a0a0ec69dea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("external_subject", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("external_issuer", sa.String(length=500), nullable=True))
    op.add_column("users", sa.Column("tenant_id", sa.String(length=255), nullable=True))
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(length=512), nullable=True)
    op.create_unique_constraint(
        "uq_users_external_identity", "users", ["external_issuer", "external_subject"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_external_identity", "users", type_="unique")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=512), nullable=False
    )
    op.drop_column("users", "tenant_id")
    op.drop_column("users", "external_issuer")
    op.drop_column("users", "external_subject")
    # ### end Alembic commands ###
