"""add action worker metadata

Revision ID: 9490341f8863
Revises: b16e0e592826
Create Date: 2026-09-11 15:35:35.331602

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9490341f8863"
down_revision: str | Sequence[str] | None = "b16e0e592826"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pending_actions",
        sa.Column(
            "worker_id",
            sa.String(length=128),
            nullable=True,
        ),
    )
    op.add_column(
        "pending_actions",
        sa.Column(
            "last_heartbeat_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "pending_actions",
        sa.Column(
            "requested_roles_json",
            sa.Text(),
            nullable=False,
            server_default="[]",
        ),
    )

    op.alter_column(
        "pending_actions",
        "requested_roles_json",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pending_actions", "requested_roles_json")
    op.drop_column("pending_actions", "last_heartbeat_at")
    op.drop_column("pending_actions", "worker_id")
    # ### end Alembic commands ###
