apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-support-worker
  namespace: ai-support
  labels:
    app: ai-support-worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-support-worker

  template:
    metadata:
      labels:
        app: ai-support-worker

    spec:
      serviceAccountName: ai-support-worker-sa
      terminationGracePeriodSeconds: 180
      containers:
        - name: worker

          image: ai-it-support-assistant:latest
          imagePullPolicy: IfNotPresent

          command:
            - python
            - -m
            - ai_it_support_assistant.worker.main

          envFrom:
            - configMapRef:
                name: ai-support-config

            - secretRef:
                name: ai-support-secrets

          env:
            - name: ACTION_WORKER_ENABLED
              value: "true"

            - name: KUBERNETES_CONFIG_MODE
              value: "incluster"

            - name: KUBERNETES_WRITE_ENABLED
              value: "true"

            - name: KUBERNETES_RESTART_ALLOWED_NAMESPACES
              value: "ai-support"

            - name: KUBERNETES_RESTART_ALLOWED_DEPLOYMENTS
              value: "restart-test"

          ports:
            - name: metrics
              containerPort: 9101

          startupProbe:
            tcpSocket:
              port: metrics
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30

          livenessProbe:
            tcpSocket:
              port: metrics
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"